import {
  ATTEMPT_ID,
  EXPERIMENT_ID,
  ISO_DATE,
  defineSchemaFixtureTests,
} from './schema-test-helper.js';

defineSchemaFixtureTests({
  schemaFile: 'session-digest.schema.json',
  suiteName: 'session-digest.schema',
  validFixture: {
    schemaVersion: 'vibe-env.session-digest.v1',
    digestId: 'DIGEST-S-003',
    sourceSessionId: 'S-003',
    generatedAt: ISO_DATE,
    activeFlow: 'results',
    lastCommand: '/flow-results',
    nextActions: ['review packaged bundle for EXP-001'],
    blockers: ['EXP-002 missing dataset'],
    experimentIds: [EXPERIMENT_ID],
    decisionIds: ['DEC-2026-04-02-001'],
    attemptIds: [ATTEMPT_ID],
    warnings: [],
  },
  invalidFixture: {
    schemaVersion: 'vibe-env.session-digest.v1',
    digestId: 'digest-s-003',
    sourceSessionId: 'S-003',
    generatedAt: ISO_DATE,
    activeFlow: 'results',
    lastCommand: '/flow-results',
    nextActions: [],
    blockers: [],
    experimentIds: [EXPERIMENT_ID],
    decisionIds: [],
    attemptIds: ['BAD-ATTEMPT'],
    warnings: [],
  },
  degradedFixture: {
    schemaVersion: 'vibe-env.session-digest.v1',
    digestId: 'DIGEST-unspecified',
    sourceSessionId: null,
    generatedAt: null,
    activeFlow: null,
    lastCommand: null,
    nextActions: [],
    blockers: [],
    experimentIds: [],
    decisionIds: [],
    attemptIds: [],
    warnings: ['No canonical sourceSessionId was available.'],
  },
});
